languageName = "Français"
contentDir = "content/fr"
languageCode = "fr-FR"
[params]
title = "Becko Jr."
subtitle = "Blog personnel"
owner = "Becko Jr."
keywords = "Cloud, DevOps"
copyright = ""
menuMore = "Plus"
readMore = "Continuer la lecture"
readOtherPosts = "Autres publications"
newerPosts = "Publications récentes"
olderPosts = "Anciennes publications"
missingContentMessage = "Page inexistante..."
missingBackButtonLabel = "Retour à la page d'accueil"
minuteReadingTime = "min de lecture"
words = "mots"

[params.logo]
logoText = "Becko Jr."
logoHomeLink = "/fr"

[menu]
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/fr/blog"
[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/fr/notes"
[[menu.main]]
identifier = "projects"
name = "Projets"
url = "/fr/projects"
